### PR TITLE
added error class, drown variable, and setters

### PR DESCRIPTION
**Pull request by anardek**
For some reason the diff below shows the old brie.py (many commits behind) on the left. I copied the current brie.py from the master (i.e., with your reverted wave generator) and merged the changes from my branch (added an error class, drown variable, and setters), which is what is on the right. There are no changes to your test scripts, even though the diff shows so below.

### CODE REVIEW

**Comment by anardek** [comment]
One more thing @mcflugen: once you approve this pull request, can you modify the brie.py in your other pull request to reflect this current version? I think there are only a handful of changes that you'll need to copy over (wave_angle setter and the handful of other AST edits you made). I'd like to finish the rest of the modifications to brie.py to implement the new AST module so I can confirm we're using the right convolution method.

**Comment by anardek** [comment]
@mcflugen, if you are not opposed, I'm going to merge this pull request. I want to update the master.

**Comment by mcflugen** [comment]
@anardek The tests are failing for the pull request. I think it's probably only because you're missing the matlab test file.

I've just merged *master* into this branch, which *should* get the tests all passing again. Could you hold off merging until the tests are all passing? It shouldn't take long.

**Comment by mcflugen** [comment]
@anardek you can merge this if you like. I'm going to change the continuous integration testing in another branch.

**Pull request merged**
