### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request fixes the failing tests. I've fixed many of them but, many of the tests that compare *brie* to the matlab version, are still failing. I'm not sure of the cause but I'll continue to have a look.

@anardek do you have any ideas as to what change may have caused the tests to start failing? This seems to have started after the merge of either #4 or #6 but it could easily be something else.

### CODE REVIEW

**Comment by anardek** [comment]
If I remember right, your version of brie in the AlongshoreTransporter commit did not have the updated version of brie for seeding wave_angle. Maybe it got lost along the way. I can work on fixing this afternoon; trying to rebase branches and commit my changes to the master atm. Then I'll work on brie.

**Comment by mcflugen** [comment]
@anardek I think I've fixed most of the errors now. Please have a look. The main one was, as you say, getting the current wave angle if it was provided as a time series. It looks like there may still be a couple of errors remaining though.

**Review by anardek — APPROVED** [review]
all looks good to me

**Comment by mcflugen** [comment]
@anardek The tests still aren't passing. Will you please have a look? There are a couple of comparisons with *q_inlet* of the matlab version that don't match (but used to, I think).

**Comment by anardek** [comment]
Just rebased. I'll get them to pass and push to master. I think I know
what's going on.

**Comment by mcflugen** [comment]
@anardek Thanks! 😄

Did you rename the *master* branch to *master-brie*? It's fine if you did. I just wasn't sure if it was something you did or GitHub did.

**Comment by anardek** [comment]
Yes, that was me. I had two 'masters' on my local machine (one for brie and
the other for Barrier3D) and it was making things really difficult!

**Pull request merged**
