### PR TITLE
Repository clean up

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request tidies up the repository to use current best practices and, I hope, will make some of the annoying maintenance a little easier.

A summary of the changes:
* Moved the static project metadata from *setup.py* into the now-standard *pyproject.toml*.
* Added a [nox](https://nox.thea.codes/en/stable/) file to manage routine maintenance tasks like running tests, finding/removing lint (i.e. black, flake8, etc.).
* Removed a bunch of lint.
* Updated the GitHub Actions workflows.
* Updated some instructions in the contributing doc.

To use *nox*:
1. Install it with `pip install nox`
2. Run the unit tests `nox -s test`
3. Test that the notebooks run `nox -s test-notebooks`
4. Test BRIE's BMI `nox -s test-bmi`
5. Find and, where possible, fix lint `nox -s lint`

In each case, *nox* will create a new virtual environment and run the given session (as defined in *noxfile.py*) in that environment.

### CODE REVIEW

**Comment by mcflugen** [comment]
@anardek Some of the docstrings in *alongshore_transporter.py* use LaTeX for some of the equations. Although they generate beautiful looking equations where rendered as html, they are pretty difficult to read in the text file or in Python. What do you think about replacing the LaTeX with something that's more text-friendly?

For example, replacing,
```
    .. math::

        K_1 = 5.3 \cdot 10^{-6} K \left( \frac{1}{2n} \right)^{6 \over 5} \left( \frac{\sqrt{g \gamma_b}} {2 \pi} \right)^{1 \over 5}

    where:

    .. math::

        K = 0.46 \rho g^{3 \over 2}
```
with
```
    The sediment transport constant, `K_1` is calculated as follows::

        K_1 = 5.3 * 10e-6 * K / (2 * n) ** (6 / 5) * (sqrt(g * gamma_b) / (2 * pi)) ** (1 / 5)

    where::

        K = 0.46 * rho * g ** (3 / 2)
```

**Review by anardek — COMMENTED** [review]
I like the nox file!

**Comment by anardek** [comment]
> @anardek Some of the docstrings in _alongshore_transporter.py_ use LaTeX for some of the equations. Although they generate beautiful looking equations where rendered as html, they are pretty difficult to read in the text file or in Python. What do you think about replacing the LaTeX with something that's more text-friendly?
> 
> For example, replacing,
> 
> ```
>     .. math::
> 
>         K_1 = 5.3 \cdot 10^{-6} K \left( \frac{1}{2n} \right)^{6 \over 5} \left( \frac{\sqrt{g \gamma_b}} {2 \pi} \right)^{1 \over 5}
> 
>     where:
> 
>     .. math::
> 
>         K = 0.46 \rho g^{3 \over 2}
> ```
> 
> with
> 
> ```
>     The sediment transport constant, `K_1` is calculated as follows::
> 
>         K_1 = 5.3 * 10e-6 * K / (2 * n) ** (6 / 5) * (sqrt(g * gamma_b) / (2 * pi)) ** (1 / 5)
> 
>     where::
> 
>         K = 0.46 * rho * g ** (3 / 2)
> ```

Fine by me

**Comment by anardek** [comment]
I merged the pull request. Wondering if we can make just one call to `nox` so I don't have to specify the three separate commands above? (test, notebooks, lint)

**Pull request merged**
